name: Telegram Notification

on:
  workflow_run:
    workflows: ["Theme Release"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Workflow: ${{ github.workflow }} in ${{ github.repository }} (${{ github.run_id }})

            Result: ${{ job.status }}
