name: Telegram Notification

# Ref: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run

on:
  workflow_run:
    workflows: ['Theme Release']
    types:
      - completed

jobs:

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ---
            Commit message: ${{ github.event.commits[0].message }}

            Action: https://github.com/${{ github.repository }}/actions 

            Result: success

            
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ---
            Commit message: ${{ github.event.commits[0].message }}

            Action: https://github.com/${{ github.repository }}/actions 

            Result: failure
